In [30]:
from pathlib import Path

import json
import pandas as pd

import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
%autoreload

In [15]:
#レース結果テーブルの前処理
results_preprocessed = preprocessing.process_results()

In [16]:
results_preprocessed

,race_id,horse_id,jockey_id,trainer_id,rank,sex,age,weight,weight_diff,tansho_odds,popularity,impost,wakuban,umaban
0,202301010101,2021100648,1095,1128,5,1,2,434,-10,23.9,5,55.0,1,1
1,202301010101,2021100159,1157,1186,6,0,2,454,-6,61.8,7,55.0,2,2
2,202301010101,2021100265,1197,1192,7,1,2,404,-2,18.8,4,53.0,3,3
3,202301010101,2021105553,5339,1160,4,1,2,450,2,16.6,3,55.0,4,4
4,202301010101,2021101429,1170,1026,1,0,2,452,-4,1.2,1,55.0,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91331,202410030812,2020101594,1187,1135,3,0,4,446,0,35.0,10,56.0,6,11
91332,202410030812,2021104131,1018,1003,5,0,3,474,-2,4.2,2,55.0,7,12
91333,202410030812,2020103212,5212,1061,7,0,4,522,2,5.4,3,58.0,7,13
91334,202410030812,2020103550,1154,1121,10,0,4,484,6,28.1,8,58.0,8,14
91335,202410030812,2021101090,1204,1170,14,1,3,456,0,85.7,14,50.0,8,15

In [4]:
#重複チェック
results_preprocessed.duplicated(subset=["race_id","horse_id"]).sum()

np.int64(0)

In [17]:
#欠損チェック
results_preprocessed.isnull().sum()

race_id        0
horse_id       0
jockey_id      0
trainer_id     0
rank           0
sex            0
age            0
weight         0
weight_diff    0
tansho_odds    0
popularity     0
impost         0
wakuban        0
umaban         0
dtype: int64

In [18]:
#馬の過去成績テーブルの加工
horse_results_preprocessed = preprocessing.process_horse_results()

c:\Users\hisaf\KeibaAI-main\KeibaAI-training\v1_0_0\src\preprocessing.py:122: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_dir / save_filename, sep="\t")

In [20]:
horse_results_preprocessed

,horse_id,date,rank,prize,rank_diff,weather,race_type,course_len,ground_state,race_class,n_horses
0,2011106610,2024-04-29,9,0.0,4.7,3.0,0,1400,3.0,5.0,10.0
1,2011106610,2024-04-14,9,0.0,2.3,0.0,0,1300,1.0,NaN,11.0
2,2011106610,2024-03-27,5,6.0,1.1,0.0,0,1400,3.0,NaN,12.0
3,2011106610,2024-03-20,5,6.0,0.7,2.0,0,1300,2.0,NaN,11.0
4,2011106610,2024-03-06,4,9.0,1.4,1.0,0,1300,3.0,5.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...
218380,2019105111,2022-04-02,5,103.0,0.2,0.0,1,2400,0.0,2.0,8.0
218381,2019105111,2022-03-12,5,75.0,0.6,0.0,1,2000,0.0,2.0,13.0
218382,2019105111,2022-02-06,4,150.0,0.6,1.0,1,2400,0.0,2.0,10.0
218383,2019105111,2021-10-24,1,510.0,0.0,0.0,1,2000,0.0,1.0,12.0
218384,2019105111,2021-09-26,11,0.0,0.7,1.0,1,2000,0.0,0.0,16.0

In [9]:
horse_id_list = [
    2020102562,
    2020104817
]
horse_results_preprocessed.query("horse_id in @horse_id_list")

,horse_id,date,rank,prize,rank_diff,weather,race_type,course_len,ground_state,race_class,n_horses
76312,2020104817,2024-05-22,6,0.0,2.8,1.0,0,1400,0.0,NaN,10.0
76313,2020104817,2024-04-29,9,0.0,3.4,1.0,0,1400,0.0,NaN,10.0
76314,2020104817,2024-04-17,5,2.0,2.1,0.0,0,1400,1.0,NaN,10.0
76315,2020104817,2024-04-01,6,0.0,2.6,0.0,0,1400,0.0,NaN,8.0
76316,2020104817,2024-03-20,7,0.0,2.3,1.0,0,1400,0.0,NaN,8.0
76317,2020104817,2024-03-06,2,14.0,0.2,1.0,0,1400,2.0,NaN,6.0
76318,2020104817,2024-02-19,7,0.0,1.5,3.0,0,1400,3.0,NaN,9.0
76319,2020104817,2024-02-05,6,0.0,1.8,3.0,0,1400,1.0,NaN,7.0
76320,2020104817,2024-01-22,6,0.0,0.7,0.0,0,1400,2.0,NaN,9.0
76321,2020104817,2024-01-10,2,14.0,1.0,1.0,0,1400,0.0,NaN,8.0
76322,2020104817,2023-12-27,2,14.0,0.6,0.0,0,1400,0.0,NaN,7.0
76323,2020104817,2023-12-06,8,0.0,3.8,0.0,0,1400,0.0,NaN,8.0
76324,2020104817,2023-11-22,4,4.0,1.6,0.0,0,1400,0.0,NaN,8.0
76325,2020104817,2023-11-07,5,2.0,3.3,0.0,0,1400,2.0,NaN,7.0
76326,2020104817,2023-10-23,8,0.0,4.4,0.0,0,1400,0.0,NaN,9.0
76327,2020104817,2023-10-10,4,4.0,0.8,0.0,0,1400,1.0,NaN,8.0
76328,2020104817,2023-09-26,6,0.0,2.6,1.0,0,1400,0.0,NaN,7.0
76329,2020104817,2023-09-13,4,4.5,2.7,0.0,0,1400,0.0,NaN,10.0
76330,2020104817,2023-08-16,5,2.2,3.0,1.0,0,1400,2.0,NaN,8.0
76331,2020104817,2023-08-02,3,9.0,2.2,0.0,0,1400,0.0,NaN,10.0
76332,2020104817,2023-06-21,3,9.0,1.6,1.0,0,1400,0.0,NaN,8.0
76333,2020104817,2023-05-31,4,12.0,2.5,1.0,0,1400,2.0,NaN,7.0
76334,2020104817,2023-05-13,15,0.0,2.2,3.0,0,1300,1.0,1.0,16.0
76335,2020104817,2023-03-26,8,0.0,1.2,3.0,0,1200,3.0,1.0,16.0
76336,2020104817,2023-02-04,11,0.0,1.5,0.0,0,1400,0.0,1.0,16.0
76337,2020104817,2023-01-05,6,0.0,1.4,0.0,0,1200,0.0,1.0,16.0
76338,2020104817,2022-11-12,10,0.0,2.2,0.0,0,1600,0.0,1.0,16.0
76339,2020104817,2022-11-06,16,0.0,4.1,0.0,1,1800,0.0,1.0,16.0
76340,2020104817,2022-08-06,15,0.0,2.0,0.0,1,1600,0.0,0.0,18.0
159857,2020102562,2024-10-19,11,0.0,1.6,0.0,0,1400,0.0,3.0,16.0
159858,2020102562,2024-08-18,15,0.0,4.2,0.0,0,1800,0.0,5.0,16.0
159859,2020102562,2024-05-19,13,0.0,1.8,1.0,0,1600,0.0,5.0,15.0
159860,2020102562,2024-05-04,12,0.0,1.6,0.0,0,1600,1.0,3.0,13.0
159861,2020102562,2024-01-28,1,800.0,0.0,1.0,0,1600,0.0,2.0,14.0
159862,2020102562,2023-12-23,9,0.0,0.9,0.0,0,1200,0.0,2.0,16.0
159863,2020102562,2023-10-08,6,0.0,0.5,1.0,0,1400,0.0,2.0,15.0
159864,2020102562,2023-09-18,3,200.0,0.4,0.0,0,1200,0.0,2.0,16.0
159865,2020102562,2023-08-27,4,120.0,0.3,0.0,0,1200,0.0,2.0,15.0
159866,2020102562,2023-05-06,1,550.0,0.0,0.0,0,1400,0.0,1.0,16.0
159867,2020102562,2023-04-15,2,220.0,0.2,3.0,0,1200,1.0,1.0,15.0
159868,2020102562,2023-02-26,3,140.0,0.3,0.0,0,1200,0.0,1.0,16.0
159869,2020102562,2023-01-28,2,220.0,0.7,0.0,0,1400,0.0,1.0,16.0
159870,2020102562,2023-01-05,3,140.0,0.3,0.0,0,1200,0.0,1.0,16.0
159871,2020102562,2022-10-16,9,0.0,1.0,1.0,1,1400,0.0,0.0,18.0

In [21]:
race_info_preprocessed = preprocessing.process_race_info()

In [22]:
race_info_preprocessed

,race_id,date,race_type,around,course_len,weather,ground_state,race_class,place
0,202301010101,2023-07-22,1,0.0,1200,0.0,0,1,1
1,202301010102,2023-07-22,0,0.0,1000,0.0,0,1,1
2,202301010103,2023-07-22,0,0.0,1700,0.0,0,1,1
3,202301010104,2023-07-22,1,0.0,1500,0.0,0,1,1
4,202301010105,2023-07-22,0,0.0,1700,0.0,0,0,1
...,...,...,...,...,...,...,...,...,...
6785,202410030808,2024-07-21,0,0.0,1000,0.0,1,2,10
6786,202410030809,2024-07-21,1,0.0,2000,1.0,0,5,10
6787,202410030810,2024-07-21,1,0.0,1200,1.0,0,3,10
6788,202410030811,2024-07-21,1,0.0,1800,0.0,0,5,10
6789,202410030812,2024-07-21,0,0.0,1700,0.0,1,2,10

In [23]:
race_info_preprocessed.isnull().sum()

race_id           0
date              0
race_type         0
around          296
course_len       57
weather           5
ground_state      0
race_class        0
place             0
dtype: int64

In [24]:
fc = FeatureCreator()
features = fc.create_features()

In [25]:
features

,race_id,horse_id,date,jockey_id,trainer_id,rank,sex,age,weight,weight_diff,...,rank_1race,prize_1race,rank_3races,prize_3races,rank_5races,prize_5races,rank_10races,prize_10races,rank_1000races,prize_1000races
0,202301010101,2021100648,2023-07-22,1095,1128,5,1,2,434,-10,...,4.0,83.0,4.500000,77.500000,4.5,77.50,4.500000,77.500000,4.500000,77.500000
1,202301010101,2021100159,2023-07-22,1157,1186,6,0,2,454,-6,...,8.0,0.0,8.000000,0.000000,8.0,0.00,8.000000,0.000000,8.000000,0.000000
2,202301010101,2021100265,2023-07-22,1197,1192,7,1,2,404,-2,...,5.0,72.0,5.000000,72.000000,5.0,72.00,5.000000,72.000000,5.000000,72.000000
3,202301010101,2021105553,2023-07-22,5339,1160,4,1,2,450,2,...,4.0,110.0,4.000000,110.000000,4.0,110.00,4.000000,110.000000,4.000000,110.000000
4,202301010101,2021101429,2023-07-22,1170,1026,1,0,2,452,-4,...,2.0,290.0,2.000000,290.000000,2.0,290.00,2.000000,290.000000,2.000000,290.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91331,202410030812,2020101594,2024-07-21,1187,1135,3,0,4,446,0,...,6.0,0.0,4.333333,106.666667,3.0,104.00,2.600000,133.300000,3.666667,114.266667
91332,202410030812,2021104131,2024-07-21,1018,1003,5,0,3,474,-2,...,4.0,120.0,4.666667,106.666667,4.0,183.24,3.285714,250.885714,3.285714,250.885714
91333,202410030812,2020103212,2024-07-21,5212,1061,7,0,4,522,2,...,1.0,800.0,4.333333,373.333333,4.0,284.00,3.833333,260.000000,3.833333,260.000000
91334,202410030812,2020103550,2024-07-21,1154,1121,10,0,4,484,6,...,8.0,0.0,5.000000,106.666667,4.2,144.00,4.300000,140.000000,5.062500,126.875000
91335,202410030812,2021101090,2024-07-21,1204,1170,14,1,3,456,0,...,12.0,0.0,8.666667,0.000000,5.8,154.00,5.500000,146.666667,5.500000,146.666667

In [26]:
features.duplicated(subset=["race_id", "horse_id"]).sum()

np.int64(0)

In [28]:
features.columns

Index(['race_id', 'horse_id', 'date', 'jockey_id', 'trainer_id', 'rank', 'sex',
       'age', 'weight', 'weight_diff', 'tansho_odds', 'popularity', 'impost',
       'wakuban', 'umaban', 'race_type', 'around', 'course_len', 'weather',
       'ground_state', 'race_class', 'place', 'rank_1race', 'prize_1race',
       'rank_3races', 'prize_3races', 'rank_5races', 'prize_5races',
       'rank_10races', 'prize_10races', 'rank_1000races', 'prize_1000races'],
      dtype='object')

In [33]:
#特徴量作成
pfc = PredictionFeatureCreator()

FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\common\\data\\prediction_population\\population.csv'